apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-d8ya
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-d8ya@sha256:8de445da888501d7274a13d802b43cd081c6c4c5b2a6fa629efa57d637a6a41f
        name: my-python
        resources: {}
status: {}
